version: "3"
services:
  py:
    build:
      context: .
      dockerfile: ./Dockerfile
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    ports:
    - "8888:8888"
    - "6006:6006"
    volumes:
        - ./repo:/home/ec2-user/src
