version: '3'  
services:  
  jupyter:  
    build:
      context: .
    environment:  
      JUPYTER_ENABLE_LAB: "yes" 
    ports:  
      - "8888:8888"  
    working_dir: /jupyter
    volumes:  
      - ../:/jupyter
volumes:
  jupyter-data:
